name: CI
on: [push]
jobs:
  build:
    name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Bun
        uses: oven-sh/setup-bun@v1.1.1

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun run test --ci --coverage --maxWorkers=2

      - name: Build
        run: bun run build
